server:
  port: 8888

spring:
  application:
    name: config-server
    
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Manideep12222385/demo22_microservices_config-server
          clone-on-start: true